version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/nodejs
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 60
      runas: root

